In [4]:
import pandas as pd
import numpy as np

In [5]:
l1 = [1,2,3,4,5,6,7,8]
s1 = pd.Series(l1)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [6]:
arr = np.arange(2,10, 2)
arr

array([2, 4, 6, 8])

In [8]:
s2 = pd.Series(arr)
s2

0    2
1    4
2    6
3    8
dtype: int64

# From Dictionary

In [10]:
person1 = {
    "name": ["Smith", "Allen", "John"],
    "age": [20,32,24],
    "job": ["SDE", "HR", "Sales"]
}
df1 = pd.DataFrame(person1)
df1

    name  age    job
0  Smith   20    SDE
1  Allen   32     HR
2   John   24  Sales

In [11]:
df2 = pd.DataFrame({
    "name": ["Smith", "Allen", "John"],
    "age": [20,32,24],
    "job": ["SDE", "HR", "Sales"]
})
df2

    name  age    job
0  Smith   20    SDE
1  Allen   32     HR
2   John   24  Sales

# From List

In [14]:
df3 = pd.DataFrame([[10,20,30,40], [1,2,3,4]])
df3

    0   1   2   3
0  10  20  30  40
1   1   2   3   4

In [15]:
df4 = pd.DataFrame([[10,20,30,40], [1,2,3,4]], columns=['A','B','C','D'])
df4

    A   B   C   D
0  10  20  30  40
1   1   2   3   4

# From NumPy Array

In [16]:
arr1 = np.array([[10,20,30,40], [1,2,3,4]])
arr1

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [17]:
df5 = pd.DataFrame(arr1)
df5

    0   1   2   3
0  10  20  30  40
1   1   2   3   4

In [18]:
df6 = pd.DataFrame(arr1, columns=['A','B','C','D'])
df6

    A   B   C   D
0  10  20  30  40
1   1   2   3   4

# From Excel/CSV/JSON file

In [19]:
df7 = pd.read_excel('file_example.xls')
df7

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [20]:
df8 = pd.read_csv('customers-100.csv')
df8

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96.0,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,30-01-2022,http://hayes-perez.com/
96,97.0,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,-3769,605.413.3198,vkemp@ferrell.com,10-07-2021,https://novak-allison.com/
97,98.0,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,18-09-2021,https://www.ross.com/
98,99.0,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,11-08-2021,http://watkins.info/
99,100.0,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,11-03-2020,http://www.hatfield-saunders.net/

In [21]:
df9 = pd.read_json('data.json')
df9

,_id,title,author,basePrice,finalPrice,banner,details,publishedDate,rating,__v,category
0,{'$oid': '6943f616089253e26832feeb'},Harry Potter,J. K. Rowling,1200,899,https://ritikart.com/cdn/shop/files/1_7a0681a0...,Dive into the magical world of Harry Potter wi...,{'$date': '2000-10-08T18:30:00.000Z'},4.4,0,{'$oid': '6943f9a0051c5bad487628a6'}